[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"
SHELL = "/opt/homebrew/bin/fish"

[font]
size = 12
offset = { x = 0, y = 1 }

[font.normal]
family = "PlemolJP35 Console NF"
style = "Regular"

[font.bold]
family = "PlemolJP35 Console NF"
style = "Bold"

[font.italic]
family = "PlemolJP35 Console NF"
style = "Italic"

[font.bold_italic]
family = "PlemolJP35 Console NF"
style = "Bold Italic"

[keyboard]
bindings = []

[terminal.shell]
program = "/opt/homebrew/bin/zellij"
args = ["attach", "--create", "shell_daemon"]

[general]
import = ["/Users/taisei/.config/alacritty/alacritty-theme/themes/tokyo_night.toml"]

[window]
opacity = 1.0
option_as_alt = "Both"
